### ISSUE TITLE
Interviews with users of screen reader software

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ohms-law#104]
We need to do user testing with users of screen readers to get feedback on "current" sound, and how overlap of text/sound is working (or not) to support their experience - before completely finalizing sound (started another issue for this). 

Would be best if we can do user testing with more finalized version, and make tweaks from there. If we get access to VI students before a version from Ashton is available, then we should just use the latest version we have now, with the ~4 different current sounds.

**Comment by jessegreenberg** [comment]
We need a new version with latest descriptions deployed with phet-io to be used in the sonification wrappers.

**Comment by jessegreenberg** [comment]
Hmm, hitting an error in phet-io wrappers when running locally

> Assertion failed: When running phet-io mode, all focusable instances must be instrumented.

**Comment by jessegreenberg** [comment]
I believe the issue is fixed, here is a new version with  latest description and phet-io.

https://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.22/phet-io/ohms-law_all_phet-io.html?development&phetioStandalone&accessibility

@jbphet could you please modify wrappers to use this version? The ?accessibility query parameter is required.

**Comment by jessegreenberg** [comment]
Removing my assignment.
