### ISSUE TITLE
Final feedback on sound for Ohm's Law

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ohms-law#120]
@kathy-phet @ariel-phet 

This sim's sound is design-complete, and we'll be preparing it for RC testing soon. Included in the RC will be alternative input, full description, sound, and mobile accessibility (a first!). Our goal is to have it published by March 30th.

Please take a look at [this version](https://phet-dev.colorado.edu/html/phet-io-wrapper-sonification/1.0.0-dev.90/phet-io-wrapper-sonification/ohms-law/html/ohms-law-sonification.html?sonificationFile=sonificationOptions&voltageAndResistanceSound=2&currentSound=4&accessibility), and let me know if you have any concerns about the sound, or any preferences regarding sounds on by default vs available as an enhanced sound. If possible, please let me know any thoughts, or if you would like to meet to discuss further, by Jan. 18th.

Note on user testing:
Earlier variations of these sounds were user tested with learners with visual impairments in traditional interviews (N ~ 6), and user tested with leaners without visual impairment (college students using the sim remotely as part of a Qualtrics survey study, N ~ 150). All data indicates this style of sound implementation was preferable over others we tried. If possible given logistics, we plan to do at least 1 or 2 more interviews with learners with VI in the next month or so.

**Comment by arouinfar** [comment]
@emily-phet saw this issue pop up since I'm subscribed to the repo, so decided to check it out. Hope you don't mind the unsolicited opinion. :)

I thought it was pretty clear that the sound that changes pitch is meant to represent the current. I think the balance between the clicking slider sound and the changing current sound is good. As for default vs. enhanced, it seems like the changing current sound could be default (since it layers on additional physical meaning), but slider/reset all sounds could be included in enhanced (since they are more about activating a UI control). Given how few sounds there are in this sim, I don't think there necessarily needs to be a default/enhanced distinction, though.

I think I found a bug with the sound when using keyboard nav, so I reported it in #121.

**Comment by emily-phet** [comment]
@arouinfar Thanks for taking a look! Glad you found the mapping to be intuitive. It was surprisingly difficult to get this sound/current mapping working well - we learned a lot from this sim about using semi-continuous sounds.

**Comment by ariel-phet** [comment]
@emily-phet a few thoughts:

1. It took me a bit to recognize that the "clicks" were happening at regular intervals on the slider. I think I would leave those for "enhanced" sound personally. 

2. I think the map between the sound and the current is pretty clear, no issues with the nature of that sound. I am a little surprised that the sound "dies out" since the current is constant once you set a slider to a particular value. That was obviously an intentional choice, as long as students aren't getting confused and recognizing that the sound is mapping to the dynamic change and not giving any information about the steady state, it seems totally fine.

3. I could go either way on the "reset all" sound in terms of basic or enhanced.

**Comment by emily-phet** [comment]
@ariel-phet @arouinfar 
Thanks for the feedback!

A few notes regarding decisions on what we're moving forward with: Basic UI sounds have been intended to be on by default from the beginning (e.g., the reset all sound) - they're part of the PhET auditory branding of the sim. The circuit sound seems to have good agreement from folks to have on by default. The remaining question is the click sounds - these are primarily serving the purpose as a UI sound, and we don't think would make sense in "enhanced" alone, as they're serving a basic UI function rather than a conceptual function, it takes effort to turn "enhanced" and we want that to be obviously worthwhile to users, and not for basic UI functionality that supports use but isn't something that users should to aware of. 

We're moving ahead with all sounds on by default - keeping this sim nice and simple and consistent with it's cousin RIAW. :)

**Comment by emily-phet** [comment]
Assigning to @jbphet so he's knows final design decisions have been made.

**Comment by jbphet** [comment]
The sound has been added to the sim, and we will track any issues found elsewhere.  Closing.
