### ISSUE TITLE
StringTest overlap and short Ohm width

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ohms-law#140]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/313
I noticed that some string tests cause the voltage/resistance strings and the variables above them can overlap.  The Ohm string max width is also shorter than the corresponding V.  This is likely very minor.
**Steps to reproduce:**
1. Go to stringTest=rtl
2. Observe the voltage/resistance strings
3. Go to stringTest=double or long
4. Observe Ohm string

**Screenshots:**
![ohmsmall](https://user-images.githubusercontent.com/41024075/57093671-c291b280-6ccb-11e9-9eee-e04b3ad070fd.png)
![runstogether](https://user-images.githubusercontent.com/41024075/57093679-c6253980-6ccb-11e9-9606-2b0012758432.png)

Troubleshooting information (do not edit):

<details>

Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/ohms-law/1.4.0-rc.1/phet/ohms-law_en_phet.html?stringTest=long
Version: 1.4.0-rc.1 2019-05-01 19:41:33 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
It looks like the maxWidth for the units takes into account the width of the value. Since "500" is wider than "4.7", the ohms units are shorter. Related commit references https://github.com/phetsims/ohms-law/issues/50.

```js
      maxWidth: OhmsLawConstants.SLIDER_WIDTH - valueText.width - READOUT_SPACING,
```

The rtl issue is because the spacing of the letters symbol and label have a negative value that was chosen because it looks good with english strings.

**Comment by jessegreenberg** [comment]
@ariel-phet @zepumph do you think this issue is worth looking into? We can fix the vertical spacing issue by laying out text like https://github.com/phetsims/resistance-in-a-wire/issues/106. @zepumph can you comment on whether it is important that the maxWidth of the units be dependent on the width of the value?

**Comment by jessegreenberg** [comment]
Eh, just doing it 🐩, The above commit handles the rtl portion of the issue.

**Comment by jessegreenberg** [comment]
I tested with stringTest=long,  stringTest=double, stringTest=x, stringTest=rtl to make sure that #134 was still fixed after the change. Should be ready for verification in the next RC.

**Comment by jessegreenberg** [comment]
Pushed to 1.4.

**Comment by KatieWoe** [comment]
Looks good in 1.4.0-rc.3
