### ISSUE TITLE
Safari sliders freeze after sitting

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ohms-law#146]
**Device**
Jordan
**OS**
Mac 10.14.5
**Browser**
Safari 12.1.1
**Problem Description**
For https://github.com/phetsims/QA/issues/327.  Fairly serious, sorry for not catching it earlier.  Went and checked rc-1 and it was there, but does not seem to be in either the published version of ohms-law or resistance in a wire.  Only seen on safari so far.  When the sim is left to sit for ~1 min, the sliders will not move for several seconds.  The cursor does not become a hand, and a staticy version of the sound will play while you attempt to drag. @jbphet as well in case it is related to sound somehow.
**Steps to Reproduce**
1. Move the sliders up or down
2. Move the cursor away from the sliders
3. Leave the sim to sit for about a minute without leaving tab or window (I made an issue on a different computer)
4. Return to the sim and attempt to drag a slider

**Screenshots**
![freezessafari](https://user-images.githubusercontent.com/41024075/58574147-91d66780-81fc-11e9-87dd-66a218f61ed8.gif)

**Comment by jessegreenberg** [comment]
Bummer, thanks for finding @KatieWoe. I don't have access to Safari now, so would you mind testing to see if this happens if sound is disabled?

https://phet-dev.colorado.edu/html/ohms-law/1.4.0-rc.3/phet/ohms-law_en_phet.html?sound=disabled

This also looks similar to https://github.com/phetsims/joist/issues/140, but may not be related.

**Comment by jessegreenberg** [comment]
When this happens do you see any errors show up in the dev console?

**Comment by jessegreenberg** [comment]
@KatieWoe and I took a look at this over screen share. We were able to consistently see this with and without sound enabled from the button in the navigation bar on the RC. But we were NOT able to see this in any other sim. We also did not see this on master ohms-law either! So we are thinking that something has since changed that fixed this since 1.4 SHAs.

I am going to look through some commit history in case anything shows up that is obvious that we can patch. It would be unfortunate to start from master again.

@jbphet are you aware of any changes in tambo that might have fixed this since 1.4 Shas were taken (Wed May 01 2019 15:39:35)

**Comment by KatieWoe** [comment]
It does happen on an older version of safari too.

**Comment by jessegreenberg** [comment]
I searched through scenery, joist, and others but didn't see anything obvious. Lots of changes everywhere so it was a long shot.

@kathy-phet capacitor-lab-basics SHAs were taken roughly the same time as OL, can you please see if it happens in https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.2/phet/capacitor-lab-basics_all_phet.html after dragging and moving something?

**Comment by KatieWoe** [comment]
@jessegreenberg didn't see anything there

**Comment by jessegreenberg** [comment]
@KatieWoe can you please do a triple check that this built version from master doesn't exhibit the issue? I realized we had only tested RequireJS.
https://phet-dev.colorado.edu/html/ohms-law/1.5.0-dev.1/phet/ohms-law_en_phet.html

**Comment by KatieWoe** [comment]
@jessegreenberg just checked.  It does happen on built version from master

**Comment by jbphet** [comment]
I think I must have been working on this at the same time as @KatieWoe, and I came to the same conclusion about the problem existing on the current master version (i.e. it does exist there).  I tried quite a number of experiments, below are my notes.  The last one is probably the most significant.

I was testing with the MacBook Pro named "Dirac", OSX version 10.10.5, Safari version 10.1.2.

+ For me to reproduce it consistently, I had to wait longer than 1 minute.  I basically used my phone to set a 2 minute countdown timer, and the problem was very reproducible after that amount of time.
+ The problem is occurring on master.
+ The "staticy" sound that @KatieWoe refers to in the opening comment above is the sound that is intentionally played as the voltage or resistance value changes, and it is playing correctly, which is surprising since nothing else seems to be happening.  This would seem to indicate that the code is not blocked, but rendering is.
+ If I add in a bunch of printouts to monitor the values of voltage, resistance, and current, the values don't get printed until things get unstuck, even though the sounds triggered by the resistance/voltage changes DO play.
+ If I remove all sound generators, the problem still occurs, which I interpret as meaning that the problem isn't due to sound generation.

I'd love to continue to work to track this down, but since it seems like it is probably not due to sound generation (and because I'm out tomorrow), I'm going to leave it to @jessegreenberg for the next steps.

**Comment by jessegreenberg** [comment]
I just tried to reproduce this using the macincloud service we subscribe to but I wasn't able to see the bug there after waiting for 2 minutes. System is macOS 10.14.4 Safari 12.1.

**Comment by jessegreenberg** [comment]
Since I cannot reproduce this I am not sure how I can debug any further. @ariel-phet could I have some assistance with this? From @jbphet notes above, this might be due to rendering in Safari so @jonathanolson could know the most about this.

**Comment by jbphet** [comment]
@jessegreenberg - I'd forgotten that you don't have access to a Mac.  I think having @jonathanolson take a look is a good idea, but if you decide you'd like to try to test some things remotely on a device where the problem is reproducible, let me know, and perhaps we can set up Dirac for remote access.  I poked around a bit on line, and it seems like this is definitely a supported feature.

**Comment by jessegreenberg** [comment]
That is a great suggestion, thank you @jbphet. It would be great to be able to do that for this issue and probably others in the future. I set up an issue in special-ops to set that up.

**Comment by ariel-phet** [comment]
@jbphet @jessegreenberg I know @arnabp is pretty tech savy. Could we have him try to set this up?

**Comment by jessegreenberg** [comment]
@arnabp we started this issue to try a few options: https://github.com/phetsims/special-ops/issues/137 - It would be great to have any thoughts you may have.

**Comment by jessegreenberg** [comment]
@KatieWoe set up "Dirac" for remote access through https://github.com/phetsims/special-ops/issues/137 and it is working very well, I am able to use the sim in Safari. However, I am not able to see the original issue at https://phet-dev.colorado.edu/html/ohms-law/1.4.0-rc.3/phet/ohms-law_en_phet.html, sliders are responsive after moving them and letting the sim sit for 3 minutes. I tried 4 different times to reproduce.

**Comment by jessegreenberg** [comment]
@KatieWoe also tried to produce the bug with screen share enabled and was unable to see the issue.

@KatieWoe then tried without the remote access enabled  and saw the issue right away. So I think this is looking more like https://github.com/phetsims/joist/issues/140 where safari "goes to sleep" and the screen share is preventing it from happening.

Unfortunately, we will still need someone with access to a  mac to debug this further. @ariel-phet back over to you, is there anyone else with access to a mac that would be able to work on this?

Also, I assumed this would block publication of ohms-law, but is that correct? I am still skeptical that this is a sim specific issue, I wonder if we will see it in other sims too now that we know that we need to wait longer. I asked @KatieWoe to try to produce the bug as part of  https://github.com/phetsims/QA/issues/333.

**Comment by jessegreenberg** [comment]
In phetsims/qa#333 @KatieWoe verified that this is happening in other sims in master right now. At least resistance-in-a-wire and gravity-force-lab-basics.

**Comment by jessegreenberg** [comment]
This isn't sim specific, so we will likely continue in https://github.com/phetsims/joist/issues/140 or perhaps another one if that one is not appropriate.

**Comment by jbphet** [comment]
@KatieWoe worked with @jessegreenberg to set up the remote access for a Mac, which is why this was assigned back to me.  Unassigning.

**Comment by ariel-phet** [comment]
Remote access isn't working for this particular bug. @KatieWoe thanks for setting remote access up however, that might be useful in future for some other issues, and we should make the devs aware. I will note for dev meeting on Thursday.

However, it is going to be best for this bug and future ones on this platform related to a11y for @jessegreenberg to have his own test device. I will work with Oliver to get a macbook air that runs latest OS.

**Comment by jessegreenberg** [comment]
This has been fixed in https://github.com/phetsims/joist/issues/140. scenery ohms-law 1.4 release branch needs the change then this will be ready for verification in the release.

**Comment by KatieWoe** [comment]
Looks good 1.4.0-rc.4
